---
title: ""
---

<!--Add a loading bar!-->
<script src="pace.js"></script>
<link href="pace_loadbar_loading.css" rel="stylesheet" />

<!--Create a block for title and breadcrumbs to appear on same line-->
<div style="width: 100%; display: inline-block;">
<div style="float: left;">
<h1>Data</h1>
</div>
<div style="float: right;">
<ol class="breadcrumb" style="background-color:white;">
  <li class="breadcrumb-item"><a href="index.html">Home</a></li>
  <li class="breadcrumb-item active">Data</li>
</ol>
</div>
</div>
<hr class="hr-orange">

<br>
  
<!--Begin page content!-->
The data presented are intended to show the progress and impact of dog vaccination efforts in the district from 2002 to `r substr(Sys.Date(), 1,4)`.  
A summary of the data can be downloaded below. If you use the summarised data please cite/acknowledge this website and the local government personnel in Tanzania who are delivering dog vaccinations.  
Ongoing data collection continues as part of several PhD and postdoctoral studies. Please get in contact if you are interested in collaborating on more detailed data.  
  
  * <b>Probable animal cases:</b> the number of animals bitten, the number of animals considered to be a probable Rabies case and the number of lab confirmed Rabies cases  - `r embed_data(district="Serengeti", type="animal", label="Download")`  
  * <b>Probable human exposures:</b> the number of bite victims and probable Rabies exposures, the number of bite victims that sought care overall and by probable exposure, and the number of deaths that are the direct result of Rabies - `r embed_data(district="Serengeti", type="human", label="Download")`

<hr class="hr-grey">

Additional quarterly data are available below on Rabies cases and exposures in Serengeti District. This is not available on the main website.  
  
<b>Animal Rabies cases</b><br>
`r embed_review(type="case", label="Download")`  

<b>Human Rabies exposures</b><br>
`r embed_review(type="exposure", label="Download")`  